config/routes.rb
Rails.application.routes.draw do
  resources :spins
  resources :locations
  resources :scooters
  resources :favorites
  resources :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorites
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true

    def full_name
      first_name + " " + last_name
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    Scooter.destroy_all
    Lime.destroy_all
    Jump.destroy_all
    Bird.destroy_all
    Spin.destroy_all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :bird, :lime, :jump, :spin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="error_style">
      <h5><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :bird %>
    <%= form.check_box :bird %>
  </div>

  <div class="field">
    <%= form.label :lime %>
    <%= form.check_box :lime %>
  </div>

  <div class="field">
    <%= form.label :jump %>
    <%= form.check_box :jump %>
  </div>

  <div class="field">
    <%= form.label :spin %>
    <%= form.check_box :spin %>
  </div>

  <div class="actions" id="submit_button">
    <%= form.submit 'Create/Update User', :class => 'btn btn-primary btn-large'%>
  </div>
<% end %>

app/views/users/_search_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bird %>
    <%= form.check_box :bird %>
  </div>

  <div class="field">
    <%= form.label :lime %>
    <%= form.check_box :lime %>
  </div>

  <div class="field">
    <%= form.label :jump %>
    <%= form.check_box :jump %>
  </div>

  <div class="field">
    <%= form.label :spin %>
    <%= form.check_box :spin %>
  </div>

  <div class="actions">
    <%= form.submit 'Update', :class => 'btn btn-primary btn-large' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container large text-center">
  <h3 class="text-right logo">¤ SCOOTER SLEUTH ¤</h3>

  <h2>Editing User</h2>

  <%= render 'form', user: @user %>

  <div class="card-footer header">
    | <%= link_to 'Back', user_path(@user) %> |
    <%= link_to 'Home', users_path %> |
  </div>
</div>

app/views/users/index.html.erb
<div class="container large">
  <div class="text-center">
    <h1 class="logo">¤ Scooter Sleuth ¤</h1>
    <h4>Welcome to <span class="logo_text">¤ Scooter Sleuth ¤</span>!</h4>
    <h4>Please select a user or create a new one:</h4>
  </div>

  <div class="row users_list">
    <div>
      <% @users.each do |user| %>
      <div class="user_list_element"><%= link_to user.full_name, user_path(user.id) %></div>
      <% end %>
    </div>
  </div>

  <div class="bottom_button">
    <p class="col-lg-9"></p>
    <a href="users/new" class="col-xs-6" id="new_user"><button class='btn btn-primary btn-lg'>Create New User</button></a>
  </div>
</div>

app/views/users/new.html.erb
<div class="container large text-center">
  <h3 class="text-right logo">¤ SCOOTER SLEUTH ¤</h3>

  <h2 id="new_user_header">Create New User</h2>

  <div id="new_user_form"><%= render 'form', user: @user %></div>

  <div class="card-footer header">
    | <%= link_to 'Home', users_path %> |
  </div>
</div>

app/views/users/show.html.erb
<div class="container large text-center">

  <h3 class="text-right logo">¤ SCOOTER SLEUTH ¤</h3>

  <div class="card-footer header">
    | <%= link_to 'Home', users_path %> |
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Delete', user_path(@user), method: :delete %> |
  </div>
  <p id="notice" class="notice_good"><%= notice %></p>

  <h2>Welcome <%= "#{@user.full_name}" %>!</h2>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<!-- links to updating the user -->
<%= render 'search_form', user: @user %>

  <!--  using a button to link to the locations new page -->
  <button f.submit onclick="window.location.href='/locations/new'" class="find_scooter_button btn btn-primary btn-lg">Lets Find Some Scooters!</button>

</div>