config/routes.rb
Rails.application.routes.draw do
  resources :spins
  resources :locations
  resources :scooters
  resources :favorites
  resources :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spin.rb
require 'httparty'

class Spin < ApplicationRecord
  geocoded_by [:latitude, :longitude]

  def self.get_latest
    @response = HTTParty.get('https://web.spin.pm/api/gbfs/v1/denver/free_bike_status')
    @data = JSON.parse(@response.body)["data"]["bikes"]
  end

  def self.create_scooter
    Spin.get_latest.each do |scooter|
      Spin.create(
        company: "Spin",
        latitude: scooter["lat"],
        longitude: scooter["lon"],
        battery_level: nil
      )
    end
  end

  def self.closest
    Spin.create_scooter
    Spin.near([Location.last.latitude, Location.last.longitude]).first(10)
  end

  def self.lat_array
    Spin.closest.map {|scooter| scooter.latitude}
  end

  def self.lng_array
    Spin.closest.map {|scooter| scooter.longitude}
  end

  def self.lat_lng_array
    Spin.lat_array.zip(Spin.lng_array)
  end

  def self.merge_table
    Spin.closest.each do |spin_scooter|
      Scooter.create(
        company: spin_scooter.company,
        latitude: spin_scooter.latitude,
        longitude: spin_scooter.longitude,
        battery_level: spin_scooter.battery_level
      )
    end
  end
end

app/controllers/spins_controller.rb
class SpinsController < ApplicationController
  before_action :set_spin, only: [:show, :edit, :update, :destroy]

  def index
    @spins = Spin.all
  end

  def show
  end

  def new
    @spin = Spin.new
  end

  def edit
  end

  def create
    @spin = Spin.new(spin_params)

    respond_to do |format|
      if @spin.save
        format.html { redirect_to @spin, notice: 'Spin was successfully created.' }
        format.json { render :show, status: :created, location: @spin }
      else
        format.html { render :new }
        format.json { render json: @spin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @spin.update(spin_params)
        format.html { redirect_to @spin, notice: 'Spin was successfully updated.' }
        format.json { render :show, status: :ok, location: @spin }
      else
        format.html { render :edit }
        format.json { render json: @spin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spin.destroy
    respond_to do |format|
      format.html { redirect_to spins_url, notice: 'Spin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_spin
      @spin = Spin.find(params[:id])
    end

    def spin_params
      params.require(:spin).permit(:company, :latitude, :longitude, :battery_level)
    end
end

app/helpers/spins_helper.rb
module SpinsHelper
end

app/views/spins/_form.html.erb
<%= form_with(model: spin, local: true) do |form| %>
  <% if spin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spin.errors.count, "error") %> prohibited this spin from being saved:</h2>

      <ul>
      <% spin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :battery_level %>
    <%= form.text_field :battery_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spins/edit.html.erb
<h1>Editing Spin</h1>

<%= render 'form', spin: @spin %>

<%= link_to 'Show', @spin %> |
<%= link_to 'Back', spins_path %>

app/views/spins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spins</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Battery level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spins.each do |spin| %>
      <tr>
        <td><%= spin.company %></td>
        <td><%= spin.latitude %></td>
        <td><%= spin.longitude %></td>
        <td><%= spin.battery_level %></td>
        <td><%= link_to 'Show', spin %></td>
        <td><%= link_to 'Edit', edit_spin_path(spin) %></td>
        <td><%= link_to 'Destroy', spin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spin', new_spin_path %>

app/views/spins/new.html.erb
<h1>New Spin</h1>

<%= render 'form', spin: @spin %>

<%= link_to 'Back', spins_path %>

app/views/spins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @spin.company %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @spin.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @spin.longitude %>
</p>

<p>
  <strong>Battery level:</strong>
  <%= @spin.battery_level %>
</p>

<%= link_to 'Edit', edit_spin_path(@spin) %> |
<%= link_to 'Back', spins_path %>