config/routes.rb
Rails.application.routes.draw do
  resources :spins
  resources :locations
  resources :scooters
  resources :favorites
  resources :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
require 'rest-client'
require 'json'
require 'mapquest'

class Location < ApplicationRecord
  has_many :favorites

  @@mapquest_key = Rails.application.credentials.mapquest

  @@mapquest = MapQuest.new(@@mapquest_key)

  def self.get_location(address)  #uses Mapquest to validate location and gps information
    @@data = @@mapquest.geocoding.address(address)
  end

  def self.create_location
    @@data.locations.each do |location|
      address = "#{location[:street]}, #{location[:adminArea5]}, #{location[:adminArea3]} #{location[:postalCode]}"
      lat = location[:latLng][:lat]
      lng = location[:latLng][:lng]
      Location.create(address: address, latitude: lat, longitude: lng)
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
    @closest_scooters = Scooter.populate_scooters


    @bird_battery = Bird.avg_battery_level
    @lime_battery = Lime.avg_battery_num
    @jump_battery = Jump.avg_battery_level
    @spin_battery = "information unavailable"

    @num_of_bird = Bird.all.length
    @num_of_lime = Lime.all.length
    @num_of_jump = Jump.all.length
    @num_of_spin = Spin.all.length

    @birds = Bird.lat_lng_array
    @limes = Lime.lat_lng_array
    @jumps = Jump.lat_lng_array
    @spins = Spin.lat_lng_array

    @location_lat = Location.last.latitude
    @location_lng = Location.last.longitude

  end

  def new
    @location = Location.new
  end

  def edit
  end

  def create
    address = params["location"]["address"]
    mapquest_response = Location.get_location(address)
    geocode_quality = mapquest_response.response[:results][0][:locations][0][:geocodeQualityCode]

    respond_to do |format|
      if geocode_quality == "P1AAA"
        Location.create_location
        format.html { redirect_to location_path(:id => Location.last.id)}
      else
        format.html { redirect_to new_location_path, notice: 'Please enter a more accurate address'}
      end
    end
  end

  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :latitude, :longitude)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>


<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" 			    title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" 			    title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

app/views/locations/new.html.erb
<div class="container large text-center">
  <h3 class="text-right logo">¤ SCOOTER SLEUTH ¤</h3>

  <h2>Enter Your Current Location:</h2>

  <p id="notice_error" class="error_style"><%= notice %></p>

  <div>
    <%= form_for :location, url: locations_path do |f| %>
      <%= f.label :address %>
      <%= f.text_field :address %>
      <%= f.submit 'Add Location', :class => 'btn btn-primary btn-large' %>
    <% end %>
  </div>

  <div class="card-footer header">
    | <%= link_to 'Home', users_path %> |
  </div>
</div>

app/views/locations/show.html.erb
<% provide :head_tags do %>
<script type="text/javascript" src='/locations.js'></script>
<meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        plotMarkers(<%=@birds%>, <%=@limes%>, <%=@jumps%>, <%=@spins%>, <%=@location_lat%>, <%=@location_lng%>)
    });
    </script>
<% end %>


<div class="container large text-center">
  <div class="card-footer header">
    <%= link_to 'Home', users_path %>
  </div>

  <h3 class="text-right logo">¤ SCOOTER SLEUTH ¤</h3>
   <h3 class="text-center">Scooters Near You:</h3>
  <section id="map"></section>

  <div class="footer">
    <div class="row">
      <div class="col-sm col1">
        <div class="row">
          <div class="col-sm-2">
            <img src="https://i.imgur.com/vjwfGlu.png">
          </div>
          <div class="col-sm-10">
            Bird scooters near me: <%= @num_of_bird %></br>
            Average Bird battery level: <%= @bird_battery %>
          </div>
        </div>
      </div>
      <div class="col-sm col2">
        <div class="row">
          <div class="col-sm-2">
            <img src="https://i.imgur.com/2Z46Omm.png">
          </div>
          <div class="col-sm-10">
            Jump bikes near me: <%= @num_of_jump %></br>
            Average Jump battery level: <%= @jump_battery %>
          </div>
        </div>
      </div>
      <div class="col-sm col3">
        <div class="row">
          <div class="col-sm-2">
            <img src="https://i.imgur.com/IfAWHc6.png">
          </div>
          <div class="col-sm-10">
            Lime scooters near me: <%= @num_of_lime %></br>
            Average Lime battery level: <%= @lime_battery %>
          </div>
        </div>
      </div>
      <div class="col-sm col3">
        <div class="row">
          <div class="col-sm-2">
            <img src="https://i.imgur.com/8rpLmdm.png">
          </div>
          <div class="col-sm-10">
            Spin scooters near me: <%= @num_of_spin %></br>
            Average Spin battery level: <%= @spin_battery %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>